# CONFIG PUSHPUSH

triggerBlockToJoin: NOTE_BLOCK
triggerBlockToJoinForwardForce : 2.0
triggerBlockToJoinUpwardForce : 1.8
triggerBlockDeath: RED_TERRACOTTA
knockbackMultiplier: 0.05
knockbackMultiplierUp: 0.02
doubleJumpForce: 1.0

