name: PushPush
version: '${project.version}'
main: org.snoutlabs.pushpush.PushPush
api-version: '1.20'

commands:
  pushpush:
    description : main command for pushpush plugin
    usage: /<command> [join/leave]
